# https://www.gitpod.io/docs/config-gitpod-file

image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: notify

tasks:

  - init: npm install
    command: npm run setup && npm run dev

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - bradlc.vscode-tailwindcss
